[[constraint]]
  name = "github.com/docker/machine"
  source = "github.com/kubermatic/machine"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.8.0"

[[constraint]]
  name = "github.com/kube-node/nodeset"
  branch = "master"

[[constraint]]
  name = "github.com/golang/glog"
  branch = "master"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.9"
